/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppNavbar {
    }
    interface InputComponent {
    }
    interface VinDecoder {
        "vin": string;
    }
}
export interface InputComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputComponentElement;
}
declare global {
    interface HTMLAppNavbarElement extends Components.AppNavbar, HTMLStencilElement {
    }
    var HTMLAppNavbarElement: {
        prototype: HTMLAppNavbarElement;
        new (): HTMLAppNavbarElement;
    };
    interface HTMLInputComponentElement extends Components.InputComponent, HTMLStencilElement {
    }
    var HTMLInputComponentElement: {
        prototype: HTMLInputComponentElement;
        new (): HTMLInputComponentElement;
    };
    interface HTMLVinDecoderElement extends Components.VinDecoder, HTMLStencilElement {
    }
    var HTMLVinDecoderElement: {
        prototype: HTMLVinDecoderElement;
        new (): HTMLVinDecoderElement;
    };
    interface HTMLElementTagNameMap {
        "app-navbar": HTMLAppNavbarElement;
        "input-component": HTMLInputComponentElement;
        "vin-decoder": HTMLVinDecoderElement;
    }
}
declare namespace LocalJSX {
    interface AppNavbar {
    }
    interface InputComponent {
        "onFetchDataEvent"?: (event: InputComponentCustomEvent<string>) => void;
    }
    interface VinDecoder {
        "vin"?: string;
    }
    interface IntrinsicElements {
        "app-navbar": AppNavbar;
        "input-component": InputComponent;
        "vin-decoder": VinDecoder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-navbar": LocalJSX.AppNavbar & JSXBase.HTMLAttributes<HTMLAppNavbarElement>;
            "input-component": LocalJSX.InputComponent & JSXBase.HTMLAttributes<HTMLInputComponentElement>;
            "vin-decoder": LocalJSX.VinDecoder & JSXBase.HTMLAttributes<HTMLVinDecoderElement>;
        }
    }
}
